### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by PhlegethonAcheron** [JohnsonM20/OpenTrivia#1]
I just wanted to say hi, how's it going? I can't actually text, because the iPad was taken away, and you still haven't accepted my friend request on Discord, so this is the next best way to say hello! 
If you don't remember, it's Townsend from Tufts PAD

**Comment by JohnsonM20** [comment]
Hey, I accepted your request on Discord I think, did you get it?

**Comment by PhlegethonAcheron** [comment]
I responded to you on discord, you should be able to see that.
